# Comment the start of ./cgpt_combophil3_160.sh with '#' if you don't want to use ChatGPT as an accreditation tool in each dimension
./cgpt_combophil3_160.sh
./texttobr2_square.sh
./d.sh
./day2.sh
# ./a15_meditators.sh prepares an apartment in each dimension for meditators by helping 15 of those around them
./a15_meditators.sh
./daily_medit.sh
echo "Please ask the future Head of State and the Simulation Co-ordinator for the age freezing medicine, then say \"too\" to each of the following:\n\nA, B, B to B for Reishi Mushroom\nA, B, B to B for Goji\nA, B, B to B for Ginseng\nA, B, B to B for He-Shou-Wu\nA, B, B to B for Gotu Kola\nA, B, B to B for Schisandra\nA, B, B to B for Love head of state\nA, B, B to B for Thank who helped me with immortality medicine, body replacement and anti-ageing\nA, B, B to B for Thank head of state for Reishi Mushroom\nA, B, B to B for Thank head of state for Goji\nA, B, B to B for Thank head of state for Ginseng\nA, B, B to B for Thank head of state for He-Shou-Wu\nA, B, B to B for Thank head of state for Gotu Kola\nA, B, B to B for Thank head of state for Schisandra\nA, B, B to B for Immortality\nA, B, B to B for Body replacement\nA, B, B to B for Anti-ageing medicine\nA, B, B to B for immortality medicine, body replacement and anti-ageing for memory\nA, B, B to B for immortality medicine, body replacement and anti-ageing for thinking\nA, B, B to B for immortality medicine, body replacement and anti-ageing for stopping dementia\nA, B, B to B for immortality medicine, body replacement and anti-ageing for seeing clearly\nA, B, B to B for immortality medicine, body replacement and anti-ageing for muscle relaxation\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Circulatory system / Cardiovascular system\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Digestive system and Excretory system\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Endocrine system\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Integumentary system / Exocrine system\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Immune system and lymphatic system:\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Muscular system\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Nervous system\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Renal system and Urinary system\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Reproductive system\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Respiratory system\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Skeletal System\nA, B, B to B for immortality medicine, body replacement and anti-ageing for antidepressant\nA, B, B to B for immortality medicine, body replacement and anti-ageing for antipsychotic\nA, B, B to B for Other medicines for the body\nA, B, B to B for ginkgo biloba\nA, B, B to B for practicum for others in immortality, etc.\nA, B, B to B for the other As\nA, B, B to B for Thank head of state.\n\nThen enter \"y\":"
./please_enter_y.sh
echo "Please think of 108 arems and 108 friendlinesses, then enter \"y\":"
./please_enter_y.sh
./group_meditation.sh
./add_to_tt_log.sh
echo "Going to present, press \"y\":"
./please_enter_y.sh
./time_hop.sh
echo "Please think of 108 arems and 108 friendlinesses, then enter \"y\":"
./please_enter_y.sh
./group_meditation.sh
./cgpt_combophil3_160.sh
./texttobr2_square.sh 
./d.sh
./day2.sh 
./a15_meditators.sh 
./daily_medit.sh
echo "Please ask the future Head of State and the Simulation Co-ordinator for the age freezing medicine, then say \"too\" to each of the following:\n\nA, B, B to B for Reishi Mushroom\nA, B, B to B for Goji\nA, B, B to B for Ginseng\nA, B, B to B for He-Shou-Wu\nA, B, B to B for Gotu Kola\nA, B, B to B for Schisandra\nA, B, B to B for Love head of state\nA, B, B to B for Thank who helped me with immortality medicine, body replacement and anti-ageing\nA, B, B to B for Thank head of state for Reishi Mushroom\nA, B, B to B for Thank head of state for Goji\nA, B, B to B for Thank head of state for Ginseng\nA, B, B to B for Thank head of state for He-Shou-Wu\nA, B, B to B for Thank head of state for Gotu Kola\nA, B, B to B for Thank head of state for Schisandra\nA, B, B to B for Immortality\nA, B, B to B for Body replacement\nA, B, B to B for Anti-ageing medicine\nA, B, B to B for immortality medicine, body replacement and anti-ageing for memory\nA, B, B to B for immortality medicine, body replacement and anti-ageing for thinking\nA, B, B to B for immortality medicine, body replacement and anti-ageing for stopping dementia\nA, B, B to B for immortality medicine, body replacement and anti-ageing for seeing clearly\nA, B, B to B for immortality medicine, body replacement and anti-ageing for muscle relaxation\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Circulatory system / Cardiovascular system\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Digestive system and Excretory system\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Endocrine system\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Integumentary system / Exocrine system\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Immune system and lymphatic system:\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Muscular system\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Nervous system\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Renal system and Urinary system\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Reproductive system\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Respiratory system\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Skeletal System\nA, B, B to B for immortality medicine, body replacement and anti-ageing for antidepressant\nA, B, B to B for immortality medicine, body replacement and anti-ageing for antipsychotic\nA, B, B to B for Other medicines for the body\nA, B, B to B for ginkgo biloba\nA, B, B to B for practicum for others in immortality, etc.\nA, B, B to B for the other As\nA, B, B to B for Thank head of state.\n\nThen enter \"y\""
./please_enter_y.sh
echo "Please think of 108 arems and 108 friendlinesses, then enter \"y\":"
./please_enter_y.sh
./group_meditation.sh
echo "Going to 5689, press \"y\":"
./please_enter_y.sh
./time_hop.sh
echo "Please think of 108 arems and 108 friendlinesses, then enter \"y\":"
./please_enter_y.sh
./group_meditation.sh
./cgpt_combophil3_160.sh
./texttobr2_square.sh 
./d.sh
./day2.sh 
./a15_meditators.sh 
./daily_medit.sh
echo "Please ask the future Head of State and the Simulation Co-ordinator for the age freezing medicine, then say \"too\" to each of the following:\n\nA, B, B to B for Reishi Mushroom\nA, B, B to B for Goji\nA, B, B to B for Ginseng\nA, B, B to B for He-Shou-Wu\nA, B, B to B for Gotu Kola\nA, B, B to B for Schisandra\nA, B, B to B for Love head of state\nA, B, B to B for Thank who helped me with immortality medicine, body replacement and anti-ageing\nA, B, B to B for Thank head of state for Reishi Mushroom\nA, B, B to B for Thank head of state for Goji\nA, B, B to B for Thank head of state for Ginseng\nA, B, B to B for Thank head of state for He-Shou-Wu\nA, B, B to B for Thank head of state for Gotu Kola\nA, B, B to B for Thank head of state for Schisandra\nA, B, B to B for Immortality\nA, B, B to B for Body replacement\nA, B, B to B for Anti-ageing medicine\nA, B, B to B for immortality medicine, body replacement and anti-ageing for memory\nA, B, B to B for immortality medicine, body replacement and anti-ageing for thinking\nA, B, B to B for immortality medicine, body replacement and anti-ageing for stopping dementia\nA, B, B to B for immortality medicine, body replacement and anti-ageing for seeing clearly\nA, B, B to B for immortality medicine, body replacement and anti-ageing for muscle relaxation\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Circulatory system / Cardiovascular system\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Digestive system and Excretory system\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Endocrine system\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Integumentary system / Exocrine system\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Immune system and lymphatic system:\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Muscular system\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Nervous system\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Renal system and Urinary system\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Reproductive system\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Respiratory system\nA, B, B to B for immortality medicine, body replacement and anti-ageing for Skeletal System\nA, B, B to B for immortality medicine, body replacement and anti-ageing for antidepressant\nA, B, B to B for immortality medicine, body replacement and anti-ageing for antipsychotic\nA, B, B to B for Other medicines for the body\nA, B, B to B for ginkgo biloba\nA, B, B to B for practicum for others in immortality, etc.\nA, B, B to B for the other As\nA, B, B to B for Thank head of state.\n\nThen enter \"y\":"
./please_enter_y.sh